[package]
name = "stealth-paint"
version = "0.1.0"
authors = ["Andreas Molzer <andreas.molzer@gmx.de>"]
edition = "2018"

[dependencies]
image-canvas = { path = "../image-canvas" }
slotmap = "1"
wgpu = "0.6.2"

[build-dependencies]
shaderc = "0.7"
