[package]
name = "stealth-paint"
version = "0.1.0"
authors = ["Andreas Molzer <andreas.molzer@gmx.de>"]
edition = "2018"
license = "MPL-2.0"

[dependencies]
image-canvas = { path = "../image-canvas" }
slotmap = "1"
wgpu = "0.7"

[dependencies.image]
version = "0.23.12"
default-features = false

[build-dependencies]
shaderc = "0.7"

[dev-dependencies]
image = "0.23.13"

[[test]]
name = "blend"
