[package]
name = "stealth-paint-editor"
version = "0.0.0"
authors = ["Andreas Molzer <andreas.molzer@gmx.de>"]
edition = "2021"
license = "MPL-2.0"
resolver = "2"

# Wasm compatibility following, roughly
# <https://sotrh.github.io/learn-wgpu/beginner/tutorial1-window/#the-code>
[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "stealth-paint-editor"
path = "src/main.rs"


[dependencies.stealth-paint]
path = "../../"

## 'Optional' dependencies for the binary.
# [dependencies.egui]
# version = "0.18"
# [dependencies.egui-wgpu]
# version = "0.18"
[dependencies.image]
version = "0.24"
default-features = false
features = ["png"]
[dependencies.log]
version = "0.4"
[dependencies.winit]
version = "0.26"
[dependencies.wgpu]
version = "0.13"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
env_logger = "0.9.0"

# Wasm compatibility following, roughly
# <https://sotrh.github.io/learn-wgpu/beginner/tutorial1-window/#the-code>
[target.'cfg(target_arch = "wasm32")'.dependencies]
console_log = { version = "0.2.0" }
console_error_panic_hook = { version = "0.1.7" }
wgpu = { version = "0.13", features = ["webgl"]}
wasm-bindgen = "=0.2.82"
wasm-bindgen-futures = "0.4.30"
web-sys = { version = "=0.3.58", features = [
    "Document",
    "Window",
    "Element",
]}
