[package]
name = "zosimos-editor"
version = "0.0.0"
authors = ["Andreas Molzer <andreas.molzer@gmx.de>"]
edition = "2021"
license = "MPL-2.0"

# Wasm compatibility following, roughly
# <https://sotrh.github.io/learn-wgpu/beginner/tutorial1-window/#the-code>
[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "zosimos-editor"
path = "src/main.rs"


[dependencies]
zosimos.workspace = true

[dependencies.arc-swap]
version = "1.6"
## 'Optional' dependencies for the binary.
# [dependencies.egui]
# version = "0.18"
# [dependencies.egui-wgpu]
# version = "0.18"
[dependencies.image]
version = "0.25"
default-features = false
features = ["png"]
[dependencies.log]
version = "0.4"
[dependencies.waker-fn]
version = "1.1"
[dependencies.winit]
version = "0.30"
[dependencies.wgpu]
workspace = true

[dependencies.env_logger]
version = "0.9.0"

# Wasm compatibility following, roughly
# <https://sotrh.github.io/learn-wgpu/beginner/tutorial1-window/#the-code>
[target.'cfg(target_arch = "wasm32")'.dependencies]
console_log = { version = "0.2.0" }
console_error_panic_hook = { version = "0.1.7" }
wgpu = { version = "*", features = ["webgl"]}
wasm-bindgen = "^0.2.97"
wasm-bindgen-futures = "0.4.42"
web-sys = { version = "^0.3.74", features = [
    "Document",
    "Window",
    "Element",
]}
