name: Rust CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable, nightly]
        target:
        # Not relevant right now, we should only build core binaries here.
        # - "x86_64-unknown-linux-gnu"
        - "wasm32-wasip1"
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ matrix.rust }}
        target: ${{ matrix.target }}
    - name: Cache Cargo Dependencies
      uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: true
    - name: build
      run: >
        cargo build --verbose --target ${{ matrix.target }}

  rustfmt:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        override: true
        components: rustfmt
        target: wasm32-wasip1
    - name: Cache Cargo Dependencies
      uses: Swatinem/rust-cache@v2
      with:
        save-if: "false"
    - name: Run rustfmt check
      run: >
        cargo fmt -- --check
